# Generated by Django 3.2.4 on 2021-07-03 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_poster', '0002_alter_timeslot_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name': 'Время', 'verbose_name_plural': 'Время'},
        ),
    ]
