# Generated by Django 3.2.4 on 2021-07-03 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_poster', '0003_alter_timeslot_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name': 'Время'},
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_time', to='auto_poster.schedule'),
        ),
    ]
