# Generated by Django 3.2.4 on 2021-07-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_poster', '0005_post_is_republished'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_id',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
